# Token constants
TOKEN_NAME_IGNORE_TOKEN     = "IGNORE"
TOKEN_NAME_INVALID_TOKEN    = "INVALID"

TOKEN_NAME_BREAK            = "BREAK"
TOKEN_NAME_CASE             = "CASE"
TOKEN_NAME_DEFAULT          = "DEFAULT"
TOKEN_NAME_ELSE             = "ELSE"
TOKEN_NAME_IF               = "IF"
TOKEN_NAME_INPUT            = "INPUT"
TOKEN_NAME_OUTPUT           = "OUTPUT"
TOKEN_NAME_SWITCH           = "SWITCH"
TOKEN_NAME_WHILE            = "WHILE"

TOKEN_NAME_LEFT_PRNTSS      = "LEFT_PRNTSS"
TOKEN_NAME_RIGHT_PRNTSS     = "RIGHT_PRNTSS"
TOKEN_NAME_LEFT_BRCKT       = "LEFT_BRCKT"
TOKEN_NAME_RIGHT_BRCKT      = "RIGHT_BRCKT"
TOKEN_NAME_COMMA            = "COMMA"
TOKEN_NAME_COLON            = "COLON"
TOKEN_NAME_SEMICOLON        = "SEMICOLON"
TOKEN_NAME_EQUALS           = "EQUALS"

TOKEN_NAME_RELOP            = "RELOP"
TOKEN_NAME_ADDOP            = "ADDOP"
TOKEN_NAME_MULOP            = "MULOP"
TOKEN_NAME_OR               = "OR"
TOKEN_NAME_AND              = "AND"
TOKEN_NAME_NOT              = "NOT"
TOKEN_NAME_CAST             = "CAST" 

TOKEN_NAME_ID               = "ID"
TOKEN_NAME_TYPE_INT         = "INT"
TOKEN_NAME_TYPE_FLOAT       = "FLOAT"

TOKEN_NAME_NUM              = "NUM"

# Others
GRAMMAR_FILE_PATH           = "cpl.lark"